### ISSUE TITLE
Close event does not occur on board

### ISSUE THREAD

**Issue by antoineDeRengerve** [partnering/diya-sdk#40]
Normal situation is : 
![screenshot from 2017-02-20 17-48-00](https://cloud.githubusercontent.com/assets/10978052/23135039/5041213a-f797-11e6-890c-c9d3570927c4.png)
- Upon disconnection (wifi is lost), a close event is emitted.
- An error message for ieq service is displayed.
- Ieq service retries to connect  (another close event is sent).
- When reconnection occurs, peer-connected events and an open event are emitted.
- IEQ data are received again.

Fail situation : (occurs on board)
- Disconnection occurs spontaneously (cannot associate to wifi issue or not)
- In that case, 3 among 4 peers are found disconnected (events emitted)
- No close event emitted
- No open event emitted after (even though the board is effectively connected) so the IEQ data are not received again (the IEQ subscription depends on selector changed event which occurs upon an open event).
![screenshot](https://cloud.githubusercontent.com/assets/10978052/23156971/75255520-f819-11e6-87f5-11b58429a523.png)

**Comment by nilpotence** [comment]
I should try to update diya-chooser with fixes from partnering/diya-chooser#3c12631 partnering/diya-chooser#503e7e3

**Comment by antoineDeRengerve** [comment]
Solved by updating diya-chooser.
