### ISSUE TITLE
Multiple disconnection and reconnection in the case of diya-info-screen

### ISSUE THREAD

**Issue by antoineDeRengerve** [partnering/diya-sdk#44]
Issue #40 seems to be resolved by updating diya-chooser but, there are many disconnection reconnection which seems quite odd...

Events : 
peer-disconnected
peer-connected

It also occurs on my machine locally : multiple peer-disconnected / peer-connected events (I am using wire cable)

**Comment by nilpotence** [comment]
If there are multiple peers (skynode, dock, robot, board) it is normal that multiple peer-connected / peer-disconnected are fired on connection / disconnection.

If what you mean is that it shouldn't disconnect in the first place, then it probably is a bug in diya-node networking. I'll have a look at it tomorrow.

**Comment by antoineDeRengerve** [comment]
Solved at the level of diya-node.
