### ISSUE TITLE
Data config doc update

### ISSUE THREAD

**Issue by loicbachelotPartnering** [partnering/diya-sdk#71]
Update of the doc for the data config structure: 
Add sampling in criteria.time object.
Remove or notify that operator and sampling from data config are deprecated.
remove the [ ] from sensors: [null] => sensors: null

**Comment by loicbachelotPartnering** [comment]
@antoineDeRengerve I haven't got the rights

**Comment by antoineDeRengerve** [comment]
@loicbachelotPartnering You mean you cant clone ?

**Comment by loicbachelotPartnering** [comment]
@antoineDeRengerve I can't push on a new branch
