### ISSUE TITLE
Get ieq data from specified devices and aggregated 

### ISSUE THREAD

**Issue by loicbachelotPartnering** [partnering/diya-sdk#73]
# Description
I want to get data from a specified device or multiple specified devices and also the aggregated data from all the devices on the site.

# example
watch({timeRange:timeRange, robots: ['D1R00015']}, function(data))
and watch({timeRange:timeRange, function(data))
in the same subscription with a device ID 'all' to specify we want the aggregated data:
watch({timeRange:timeRange, robots: ['D1R00015', 'all']}, function(data))

**Comment by antoineDeRengerve** [comment]
Will be done in corresponding project : see https://github.com/diya-sdk/diya-sdk-ieq/issues/5
